Introduce shared build methods
WrenSecurity/wrensec-ui pull request #26
Opened 2023-11-28 16:24 UTC by pavelhoral

This PR introduces new Node module `@wrensecurity/commons-ui-build` that contains few key gulp task configurations.

I have to admit that this brings the project closer to its previous state with Grunt. However it is still a good step towards potentially more modern build tooling in the future. This change also allows us to perform any upgrade in a more controllable fashion.

New module is supposed to be distributed as Maven artifact (we are not switching to NPM yet). Downstream projects will include it as a local dependency provided by unpack task of maven-dependency-plugin.

2023-11-28 16:40 UTC, pavelhoral commented
Hm... for some reason the build fails in GH Actions, but works completely fine on my computer. Will need to investigate it a bit. However the PR can be reviewed.

2023-11-29 08:16 UTC, karelmaxa requested changes

2023-11-29 08:16 UTC, karelmaxa commented on packages/build/scripts/build.mjs
> +await mkdir(TARGET_PATH, { recursive: true });
Target directory has already been created (see line 24).

2023-11-29 08:16 UTC, karelmaxa commented on packages/build/src/index.mjs
> + * @param {useModuleResources} [options]
The correct parameter type should be `ModuleResourcesOptions`.

2023-11-29 10:02 UTC, karelmaxa approved these changes
LGTM.

2023-11-29 10:34 UTC, merged